version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: dbapi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dbAPI"
    ports:
      - "3306:3306"          # mapeia porta do container para o host -> Server=localhost funciona
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network

volumes:
  mysql_data:

networks:
  db-network:
    driver: bridge
